SongsList/SongsList/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SongsList.Models
{
    public class Genre
    {
        public string GenreId { get; set; }
        public string Name { get; set; }
    }
}

SongsList/SongsList/Models/Song.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using SongsList.Helpers;

namespace SongsList.Models
{
    public class Song
    {
        public int SongId { get; set; }
        [Required(ErrorMessage = "Please enter the songs name")]
        public string Name { get; set; }
        [Required(ErrorMessage ="Please enter a year")]
        [RangeUntilCurrentYear(1700, ErrorMessage = "Year must be between 1700 and current year")]
        public int? Year { get; set; }
        [Required(ErrorMessage ="Please enter the rating")]
        [Range(1,5, ErrorMessage = "Rating must be set between 1 and 5")]
        public int? Rating { get; set; }
        [Required(ErrorMessage ="Please enter genre")]
        public string GenreId { get; set; }
        public Genre Genre { get; set; }

        public string Slug => Name?.Replace(' ', '-').ToLower() + '-' + Year?.ToString();
    }
}

SongsList/SongsList/Models/SongContext.cs
using Microsoft.EntityFrameworkCore;

namespace SongsList.Models
{
    public class SongContext : DbContext
    {
        public SongContext(DbContextOptions<SongContext> options) : base(options)
        {
        }

        public DbSet<Song> Songs { get; set; }
        public DbSet<Genre> Genres { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Song>().HasData(
                new Song
                {
                    SongId = 1,
                    Name = "Master of Puppets",
                    Year = 1986,
                    Rating = 5,
                    GenreId = "M"
                },
                new Song
                {
                    SongId = 2,
                    Name = "Wonderwall",
                    Year = 1995,
                    Rating = 4,
                    GenreId = "R"
                },
                 new Song
                 {
                     SongId = 3,
                     Name = "Loose Yourself",
                     Year = 2002,
                     Rating = 2,
                     GenreId="H"
                 }
                );
            modelBuilder.Entity<Genre>().HasData(
                new Genre
                {
                    GenreId = "M", Name="Metal"
                },
                new Genre
                {
                    GenreId="R", Name="Rock"
                },
                new Genre
                {
                    GenreId="C", Name="Classical"
                },
                new Genre
                {
                    GenreId = "H",
                    Name = "Hip-Hop"
                }
                );
        }
    }
}

SongsList/SongsList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SongsList.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SongsList.Controllers
{
    public class HomeController : Controller
    {
        private SongContext Context { get; set; }
        public HomeController(SongContext ctx)
        {
            Context = ctx;
        }

        public IActionResult Index()
        {
            var songs = Context.Songs.Include(m => m.Genre)
                .OrderBy(m => m.Name)
                .ToList();
            return View(songs);
        } 
    }
}

SongsList/SongsList/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using SongsList.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SongsList.Controllers
{
    public class SongController : Controller
    {
        private SongContext Context { get; set; }
        public SongController(SongContext songContext)
        {
            Context = songContext;
        }
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            ViewBag.Genres = Context.Genres.OrderBy(m => m.Name).ToList();
            return View("Edit", new Song());
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            ViewBag.Genres = Context.Genres.OrderBy(m => m.Name).ToList();
            var song = Context.Songs.Find(id);
            return View(song);
        }

        [HttpPost]
        public IActionResult Edit( Song song)
        {
            if (ModelState.IsValid)
            {
                if (song.SongId==0)
                {
                    Context.Songs.Add(song);
                }
                else
                {
                    Context.Songs.Update(song);
                }
                Context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Action = song.SongId == 0 ? "Add" : "Edit";
                ViewBag.Genres = Context.Genres.OrderBy(m => m.Name).ToList();
                return View(song);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var song = Context.Songs.Find(id);
            return View(song);
        }

        [HttpPost]
        public IActionResult Delete(Song song)
        {
                    Context.Songs.Remove(song);
                    Context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

SongsList/SongsList/Views/Home/Index.cshtml
@model List<Song>;
@{ 
    ViewBag.Title = "My Songs List";
}

<a asp-controller="Song" asp-action="Add">Add new song</a>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Year</th>
            <th>Genre</th>
            <th>Rating</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var song in Model)
        {
            <tr>
                <td>@song.Name</td>
                <td>@song.Year</td>
                <td>@song.Genre.Name</td>
                <td>@song.Rating</td>
                <td>
                    <a asp-controller="Song" asp-action="Edit" asp-route-id="@song.SongId" asp-route-slug="@song.Slug">Edit</a>
                    <a asp-controller="Song" asp-action="Delete" asp-route-id="@song.SongId"asp-route-slug="@song.Slug">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

SongsList/SongsList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SongsList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SongsList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SongsList
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>